version: 2
jobs:
  build:
    docker:
      - image: larse514/circle-ci-node-docker:latest
    working_directory: ~/serverless-rds-loader

    environment:
      - IMAGE: "larse514/rds-loader"
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      run: 
          command: |
            ls
            pwd
      - run:
          name: build docker image
          command: docker build . -t ${IMAGE}:${CIRCLE_BUILD_NUM}
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker Push
          command: docker push ${IMAGE}:${CIRCLE_BUILD_NUM}

      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml